version: "3"
services:
  php:
    image: wephp:latest
    cap_add:
      - SYS_PTRACE
    volumes:
      - "${HOME}/Documents/app:/app:rw"
      - "./php/php.ini-development:/etc/php7/php.ini"
      - "./php/php-fpm/docker.conf:/etc/php7/php-fpm.d/docker.conf"
      - "./php/php-fpm/zz-docker.conf:/etc/php7/php-fpm.d/zz-docker.conf"
    ports:
      - "6500:6000"
      - "20070:20070"
    networks:
      - web
  nginx:
    image: nginx:alpine
    cap_add:
      - SYS_PTRACE
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "${HOME}/Documents/app:/app:rw"
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - php
  redis:
    image: redis:alpine
    privileged: true
    ports:
      - "6379:6379"
    networks:
      - web
networks:
  web:
